sudo: required
language: python
cache: pip
python:
  - "3.7-dev"    # Currently, Travis CI doesn't support the stable version yet.
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
services:
  - docker
env: PYTHONPATH=app
script:
  - cp config.py.example app/data/config.py
  - pytest
  - docker-compose build
