sudo: required
language: python
cache: pip
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
services:
  - docker
env: PYTHONPATH=app
script:
  - cp config.py.example app/data/config.py
  - pytest
  - docker-compose build
