services:
  kozRandBot:
    build: .
    image: kozalo/kozrandbot
    container_name: kozrandbot
    working_dir: /home/kozRandBot
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
    - "/tmp:/tmp"
    expose:
      - "8080"
      - "8000"
    logging:
      driver: local
