version: "3"
services:
  textUtilsBot:
    build: .
    image: kozalo/kozrandbot
    container_name: kozrandbot
    hostname: kozRandBot
    working_dir: /home/kozRandBot
    restart: always
    volumes:
    - "./app/data:/home/kozRandBot/app/data"
    - "/tmp:/tmp"
