version: "3.7"
services:
  kozRandBot:
    build: .
    image: kozalo/kozrandbot
    container_name: kozrandbot
    working_dir: /home/kozRandBot
    restart: unless-stopped
    volumes:
    - "./app/data:/home/kozRandBot/app/data"
    - "/tmp:/tmp"
    expose:
      - "8080"
      - "8000"
    logging:
      driver: local
