version: "3.7"
services:
  kozRandBot:
    build: .
    image: kozalo/kozrandbot
    container_name: kozrandbot
    working_dir: /home/kozRandBot
    restart: unless-stopped
    volumes:
    - "./app/data:/home/kozRandBot/app/data"
    - "/tmp:/tmp"
    ports:
      - "127.0.0.1:8001:8000"
      - "127.0.0.1:8011:8080"
    logging:
      driver: local
